# Default initial positions for katana_400_6m180_with_controlbox's ros2_control fake system
# Near-limit park positions, clamped within URDF joint bounds.

initial_positions:
  katana_motor1_pan_joint: -3.04
  katana_motor2_lift_joint:  2.19
  katana_motor3_lift_joint: -2.1272
  katana_motor4_lift_joint: -2.02
  katana_motor5_wrist_roll_joint: -2.98
  katana_l_finger_joint: 0.0
  katana_r_finger_joint: 0.0
