#include <rclcpp/rclcpp.hpp>
#include <moveit/move_group_interface/move_group_interface.h>
#include <moveit/robot_state/robot_state.hpp>
#include <geometry_msgs/msg/pose.hpp>

int main(int argc, char** argv)
{
  
 
  rclcpp::init(argc, argv);
  
  rclcpp::NodeOptions node_options;
  node_options.automatically_declare_parameters_from_overrides(true);
  auto node = rclcpp::Node::make_shared("planar_diff_drive_test", node_options);
  
  rclcpp::executors::MultiThreadedExecutor executor;
  executor.add_node(node);
  std::thread spinner_thread([&executor]() { executor.spin(); });

  RCLCPP_INFO(node->get_logger(), "Starting Planar Diff-Drive Pre-Solve...");

  // 1. GET THE TARGET POSE FROM PARAMETE

  double target_x = node->get_parameter("x").as_double();
  double target_y = node->get_parameter("y").as_double();
  double target_z = node->get_parameter("z").as_double();

  RCLCPP_INFO(node->get_logger(), "Target Pose: X=%f, Y=%f, Z=%f", target_x, target_y, target_z);

  // 2. BASE POSE IS GIVEN DIRECTLY (no atan2 auto-parking)
  double base_park_x = node->get_parameter("pos_x").as_double();
  double base_park_y = node->get_parameter("pos_y").as_double();
  double base_park_yaw = node->get_parameter("heading").as_double();

  // Setup MoveGroup using the combined group from your SRDF
  moveit::planning_interface::MoveGroupInterface mg(node, "base_arm");
  mg.setWorkspace(-10.0, -10.0, -1.0, 10.0, 10.0, 5.0);

  geometry_msgs::msg::Pose target_pose;
  target_pose.position.x = target_x;
  target_pose.position.y = target_y;
  target_pose.position.z = target_z;
  target_pose.orientation.w = 1.0; 

  // ==========================================
  // PHASE 1: THE PRE-SOLVE
  // ==========================================
  RCLCPP_INFO(node->get_logger(), "Phase 1: Pre-solving IK for the arm...");

  moveit::core::RobotStatePtr virtual_state = mg.getCurrentState();

  // Apply the 3 variables generated by your SRDF virtual joint
  virtual_state->setVariablePosition("base_planar_joint/x", base_park_x);
  virtual_state->setVariablePosition("base_planar_joint/y", base_park_y);
  virtual_state->setVariablePosition("base_planar_joint/theta", base_park_yaw);
  virtual_state->update(); 

  // Call the arm group directly from your SRDF
  const moveit::core::JointModelGroup* arm_group = virtual_state->getJointModelGroup("arm");

  bool ik_success = virtual_state->setFromIK(arm_group, target_pose, 0.1);

  if (!ik_success) {
    RCLCPP_ERROR(node->get_logger(), "IK FAILED! Arm cannot reach target from X=%f, Y=%f, Yaw=%f", 
                 base_park_x, base_park_y, base_park_yaw);
    rclcpp::shutdown();
    return 1;
  }

  RCLCPP_INFO(node->get_logger(), "IK SUCCESS! The Planar Parking Spot works!");

  // ==========================================
  // PHASE 2: HANDING IT TO OMPL
  // ==========================================
  std::vector<double> winning_joints;
  virtual_state->copyJointGroupPositions(virtual_state->getJointModelGroup("base_arm"), winning_joints);

  mg.setJointValueTarget(winning_joints);
  mg.setPlanningTime(10.0);

  moveit::planning_interface::MoveGroupInterface::Plan plan;
  if (mg.plan(plan) == moveit::core::MoveItErrorCode::SUCCESS) {
    RCLCPP_INFO(node->get_logger(), "PLAN FOUND! Ready to execute.");
  } else {
    RCLCPP_ERROR(node->get_logger(), "OMPL failed to plan a path.");
  }
  auto exec = mg.execute(plan);
  if(exec == moveit::core::MoveItErrorCode::SUCCESS) {
    RCLCPP_INFO(node->get_logger(), "Execution successful!");
  } else {
    RCLCPP_ERROR(node->get_logger(), "Execution failed.");
  }

  rclcpp::shutdown();
  spinner_thread.join();
  return 0;
}