<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>katana_arm_gazebo</name>
  <version>1.1.2</version>
  <description>This package provides a Gazebo simulation for the Katana arm.</description>
  <author>Martin Günther</author>
  <author>Jochen Sprickerhof</author>
  <maintainer email="mguenthe@uos.de">Martin Günther</maintainer>
  <license>GPL</license>
  <url>http://ros.org/wiki/katana_arm_gazebo</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>katana_description</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>
  <depend>controller_manager</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>joint_trajectory_controller</depend>
  <depend>robot_state_publisher</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
