<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>katana</name>
  <version>1.1.2</version>
  <description>
    This package provides ROS interfaces to the Neuronics Katana 450 arm.
    It wraps the <a href="/wiki/kni">KNI</a> library for low-level communication
    with the Katana arm.
  </description>
  <author email="mguenthe@uni-osnabrueck.de">Martin Günther</author>
  <maintainer email="mguenthe@uni-osnabrueck.de">Martin Günther</maintainer>
  <license>GPL</license>
  <url type="website">http://ros.org/wiki/katana</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>kni</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>urdf</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>katana_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>action_msgs</depend>
  <depend>control_msgs</depend>
  <depend>armadillo</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
